server:
  port: 8080

spring:
  application:
    name: admin
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://3.34.181.222:8888/
logging:
  level:
    root: info

