server:
  port: 8080

spring:
  application:
    name: admin
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://a2c18381d8c21491aa52a6e4f5465c91-2090461168.us-west-2.elb.amazonaws.com:8888/
logging:
  level:
    root: info

