server:
  port: 8080

spring:
  application:
    name: admin
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://a1a8630485e9e4831ad6b1e03d923edc-1731221295.us-west-2.elb.amazonaws.com:8888/
logging:
  level:
    root: info

